export { default as ClientForm } from './form'
export { default as Input } from './inputs/input'
export { default as Layout } from './layout/layout'
export { default as Layout2 } from './layout/layout2'
export { default as ListadoClientes } from './listadoclientes'
export { default as Sidebar } from './sidebar/sidebar'
export { default as Submit } from './inputs/submit'