export * from './form'
export * from './inputs'
export { default as Layout } from './layout/layout'
export { default as Layout2 } from './layout/layout2'
export { default as ListadoClientes } from './listadoclientes'
export { default as ListadoProductos } from './listadoproductos'
export * from './pedidos'
export { default as Sidebar } from './sidebar/sidebar'